Add camera view
MicrosoftDocs/CommunityToolkit pull request #428
Opened 2024-05-28 21:26 UTC by bijington

Provides the documentation for the new `CameraView` based on PR at https://github.com/CommunityToolkit/Maui/pull/1758

2024-05-29 08:00 UTC, jfversluis reviewed
Couple of minor things

2024-05-29 08:33 UTC, bijington commented on docs/maui/views/camera-view.md
> +description: "The CameraView provides the ability to connect to a camera, display a preview from the camera and take photos."
Unless I've missed something I believe we only support image capture in v1

2024-05-29 08:46 UTC, jfversluis commented on docs/maui/views/camera-view.md
> +description: "The CameraView provides the ability to connect to a camera, display a preview from the camera and take photos."
In that case we should remove "recording videos" on line 10 😄

2024-05-29 08:49 UTC, bijington commented on docs/maui/views/camera-view.md
> +The `CameraView` provides the ability to connect to a camera, display a preview from the camera and take photos. The `CameraView` also offers the options you would expect to support taking photos and
```suggestion
The `CameraView` provides the ability to connect to a camera, display a preview from the camera and take photos. The `CameraView` also offers features to support taking photos, controlling the flash, saving captured media to a file, and offering different hooks for events.
```

2024-05-29 08:50 UTC, bijington commented on docs/maui/views/camera-view.md
> +description: "The CameraView provides the ability to connect to a camera, display a preview from the camera and take photos."
How does it look now?

2024-05-29 08:53 UTC, jfversluis commented on docs/maui/views/camera-view.md
> +description: "The CameraView provides the ability to connect to a camera, display a preview from the camera and take photos."
All good! Thanks!

2024-06-02 23:59 UTC, brminnick requested changes
Thanks Shaun! II've updated the NuGet package to `CommunityToolkit.Maui.Camera` to allow us to add future camera features in the future.

I've submitted the code changes here in this review.

2024-06-02 23:59 UTC, brminnick commented on docs/maui/get-started.md
> +**Package name:** `CommunityToolkit.Maui.CameraView`
```suggestion
**Package name:** `CommunityToolkit.Maui.Camera`
```

I've updated the NuGet package to `CommunityToolkit.Maui.Camera` to allow us to add future camera features in the future.

2024-06-02 23:59 UTC, brminnick commented on docs/maui/get-started.md
> +**Package url:** https://www.nuget.org/packages/CommunityToolkit.Maui.CameraView
```suggestion
**Package url:** https://www.nuget.org/packages/CommunityToolkit.Maui.Camera
```

I've updated the NuGet package to `CommunityToolkit.Maui.Camera` to allow us to add future camera features in the future.

2024-06-02 23:59 UTC, brminnick commented on docs/maui/get-started.md
> +In order to use the `CameraView` correctly, the `UseMauiCommunityToolkitCameraView` method must be called on the `MauiAppBuilder` class when bootstrapping an application the *MauiProgram.cs* file. Th
```suggestion
In order to use the `CameraView` correctly, the `UseMauiCommunityToolkitCamera()` method must be called on the `MauiAppBuilder` class when bootstrapping an application the *MauiProgram.cs* file. The following example shows how to perform this.
```

I've updated the NuGet package to `CommunityToolkit.Maui.Camera` to allow us to add future camera features in the future.

2024-06-02 23:59 UTC, brminnick commented on docs/maui/get-started.md
> +    .UseMauiCommunityToolkitCameraView()
```suggestion
    .UseMauiCommunityToolkitCamera()
```

I've updated the NuGet package to `CommunityToolkit.Maui.Camera` to allow us to add future camera features in the future.

2024-06-17 19:30 UTC, jfversluis approved these changes
Welcome to the .NET MAUI Community Toolkit CameraView!

2024-06-17 19:31 UTC, merged