ByteArrayToImageSourceConverter
MicrosoftDocs/CommunityToolkit pull request #66
Opened 2022-04-15 13:38 UTC by bijington

Documentation added for .NET MAUI Community Toolkit proposals:

- [Proposal] `ByteArrayToImageSourceConverter ` <https://github.com/CommunityToolkit/Maui/issues/51> includes:

2022-04-15 13:39 UTC, opbld30 commented
Docs Build status updates of commit _[00edaa2](https://github.com/bijington/CommunityToolkit/commits/00edaa2c4414f3c4e0e61d7ab34d895b4aa9836b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/TOC.yml](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/byte-array-to-image-source-converter.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/byte-array-to-image-source-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/index.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-66) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C15%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204151338545104-66%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-16T13%3A39%3A48Z&sr=b&sp=r&sig=sKnLuLZRC95oKF0vNkQPaqzF8bNT2TJ2q%2B0A0sXAwAY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-15 13:39 UTC, PRMerger18 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-15 18:12 UTC, jfversluis requested changes
Minor things and needs some conflicts resolved

2022-04-15 18:12 UTC, jfversluis commented on docs/maui/converters/byte-array-to-image-source-converter.md
> +The `DoubleToIntConverter` can be used as follows in XAML:
```suggestion
The `ByteArrayToImageSourceConverter ` can be used as follows in XAML:
```

2022-04-15 18:12 UTC, jfversluis commented on docs/maui/converters/byte-array-to-image-source-converter.md
> +				converter: new ByteArrayToImageSourceConverter()));
```suggestion
				nameof(ViewModel.DotNetBotImageByteArray),
				mode: BindingMode.OneWay,
				converter: new ByteArrayToImageSourceConverter()));
```

2022-04-15 20:11 UTC, opbld32 commented
Docs Build status updates of commit _[b538a03](https://github.com/bijington/CommunityToolkit/commits/b538a03bc00662896aa2609e3e6ebaf651b21713)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/TOC.yml](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/byte-array-to-image-source-converter.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/byte-array-to-image-source-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/index.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-66) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C15%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204152010368888-66%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-16T20%3A11%3A29Z&sr=b&sp=r&sig=LUh9q13FSMlMKoOEn0bXPqZpTSOzm3CtQmWjvzw%2FxBo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-15 20:11 UTC, PRMerger12 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-15 20:12 UTC, opbld31 commented
Docs Build status updates of commit _[c578945](https://github.com/bijington/CommunityToolkit/commits/c578945ee267417ef29ed4cda9ec7433b063c991)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/TOC.yml](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/byte-array-to-image-source-converter.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/byte-array-to-image-source-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/index.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-66) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C15%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204152011145882-66%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-16T20%3A12%3A30Z&sr=b&sp=r&sig=fcMlOWRQKjl0UBQiASQH33dw8LG6uhQlKTnADcCpOBg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-15 20:12 UTC, PRMerger12 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-15 20:13 UTC, opbld31 commented
Docs Build status updates of commit _[29e20d9](https://github.com/bijington/CommunityToolkit/commits/29e20d95e63e75d834896f49b9b342d75c668b40)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/TOC.yml](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/byte-array-to-image-source-converter.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/byte-array-to-image-source-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/index.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-66) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C15%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204152011480855-66%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-16T20%3A13%3A39Z&sr=b&sp=r&sig=F6E8BxLcHAEkGKbSxnMxw%2FKfNxZeRjG94IycvxwE5gw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-15 20:13 UTC, PRMerger15 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-19 17:53 UTC, jfversluis approved these changes

2022-04-19 17:53 UTC, jfversluis commented on docs/maui/converters/byte-array-to-image-source-converter.md
> +		Content = image;
```suggestion
	image.SetBinding(
		Image.SourceProperty,
		new Binding(
			nameof(ViewModel.DotNetBotImageByteArray),
			mode: BindingMode.OneWay,
			converter: new ByteArrayToImageSourceConverter()));

	Content = image;
```

2022-04-19 17:54 UTC, opbld32 commented
Docs Build status updates of commit _[6590853](https://github.com/bijington/CommunityToolkit/commits/65908533192428a1357189802e0cc415702417f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/TOC.yml](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/byte-array-to-image-source-converter.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/byte-array-to-image-source-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/index.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-66) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204191753101612-66%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T17%3A54%3A13Z&sr=b&sp=r&sig=cpj%2FDkuaVacEtyVntXShIhyrt4peyM22%2Btj%2FlShiLCs%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 17:54 UTC, PRMerger7 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-19 17:55 UTC, opbld31 commented
Docs Build status updates of commit _[9ebf896](https://github.com/bijington/CommunityToolkit/commits/9ebf896f263dae75a90947fcc59c0f7e902c1753)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/TOC.yml](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/byte-array-to-image-source-converter.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/byte-array-to-image-source-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/index.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-66) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204191753187588-66%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T17%3A55%3A20Z&sr=b&sp=r&sig=ixUqR5I7lqVDztwNIW6hjjy9Hk%2BiMVMxp7FYGrPqdjM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 17:55 UTC, PRMerger9 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-19 17:58 UTC, opbld33 commented
Docs Build status updates of commit _[069862e](https://github.com/bijington/CommunityToolkit/commits/069862e15a4ae9a42b8e05d17b4cd7161016a6fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/TOC.yml](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/byte-array-to-image-source-converter.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/byte-array-to-image-source-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/byte-array-to-image-source-converter?branch=pr-en-us-66) |
[docs/maui/converters/index.md](https://github.com/bijington/CommunityToolkit/blob/maui/converters/byte-array-to-image-source-converter/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-66) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C19%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204191757564113-66%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-20T17%3A58%3A44Z&sr=b&sp=r&sig=erljcftwaJ3lxboIX74%2F02HjzX1S9%2BPFw9xyyNRETz4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-19 17:58 UTC, merged

2022-04-19 17:58 UTC, PRMerger17 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 Yaml File(s) | This PR includes changes to .yml file(s) owned by another author.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.