Docs for IsNull & IsNotNull converters
MicrosoftDocs/CommunityToolkit pull request #73
Opened 2022-04-18 15:10 UTC by IeuanWalker

2022-04-18 15:11 UTC, opbld30 commented
Docs Build status updates of commit _[a7f5d50](https://github.com/IeuanWalker/CommunityToolkit/commits/a7f5d5035e27798103acbee133bf17bed034b120)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/converters/is-not-null-converter.md](https://github.com/IeuanWalker/CommunityToolkit/blob/main/docs/maui/converters/is-not-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-not-null-converter?branch=pr-en-us-73) |
[docs/maui/converters/is-null-converter.md](https://github.com/IeuanWalker/CommunityToolkit/blob/main/docs/maui/converters/is-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-null-converter?branch=pr-en-us-73) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204181511148482-73%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T15%3A11%3A51Z&sr=b&sp=r&sig=MsaFvb5PkUAbCxut6DcHC8dMos9peoBZMZJaCY%2F6Bzo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 15:11 UTC, PRMerger18 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.

2022-04-18 15:22 UTC, opbld30 commented
Docs Build status updates of commit _[ab5d67f](https://github.com/IeuanWalker/CommunityToolkit/commits/ab5d67f4119b1bd2d52a7e68a71b0206f6a13344)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/converters/index.md](https://github.com/IeuanWalker/CommunityToolkit/blob/main/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-73) |
[docs/maui/converters/is-not-null-converter.md](https://github.com/IeuanWalker/CommunityToolkit/blob/main/docs/maui/converters/is-not-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-not-null-converter?branch=pr-en-us-73) |
[docs/maui/converters/is-null-converter.md](https://github.com/IeuanWalker/CommunityToolkit/blob/main/docs/maui/converters/is-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-null-converter?branch=pr-en-us-73) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C18%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204181521273537-73%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-19T15%3A22%3A03Z&sr=b&sp=r&sig=aG8n574rHDN%2BmYrEWMz0jAcqN53lwTAuwwdjvRy6xNE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-18 15:22 UTC, PRMerger3 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-19 17:47 UTC, jfversluis requested changes
Minor code formatting, but mostly: I think the true and false return descriptions are the wrong way around :D

2022-04-19 17:47 UTC, jfversluis commented on docs/maui/converters/is-not-null-converter.md
> +		Content = label;
```suggestion
	label.SetBinding(
		Label.IsVisibleProperty,
		new Binding(nameof(ViewModels.MyObject), converter: new IsNotNullConverter()));

	Content = label;
```

2022-04-19 17:47 UTC, jfversluis commented on docs/maui/converters/is-not-null-converter.md
> +The `Convert` method returns `true` when the binded object is `null` or `false` otherwise.
```suggestion
The `Convert` method returns `false` when the binded object is `null` or `true` otherwise.
```

This is the wrong way around, no?

2022-04-20 13:26 UTC, opbld30 commented
Docs Build status updates of commit _[0976343](https://github.com/IeuanWalker/CommunityToolkit/commits/097634319626a7fa39375bc33c4baf4d2d903605)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/converters/index.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-73) |
[docs/maui/converters/is-not-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-not-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-not-null-converter?branch=pr-en-us-73) |
[docs/maui/converters/is-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-null-converter?branch=pr-en-us-73) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204201325477429-73%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T13%3A26%3A31Z&sr=b&sp=r&sig=dKYdtY9n15xunS8fIvbo%2FksVh%2FqPCdj9qrG96p5unFQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 13:26 UTC, PRMerger13 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-20 13:27 UTC, opbld33 commented
Docs Build status updates of commit _[147b599](https://github.com/IeuanWalker/CommunityToolkit/commits/147b5995891ae3fc7aa59e3dd18027ef20f92562)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/converters/index.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-73) |
[docs/maui/converters/is-not-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-not-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-not-null-converter?branch=pr-en-us-73) |
[docs/maui/converters/is-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-null-converter?branch=pr-en-us-73) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204201326212117-73%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T13%3A27%3A13Z&sr=b&sp=r&sig=AaqM2BJZ5TRJlJjP88RXrSC7m138K09TmDQkdTpPwHw%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 13:27 UTC, PRMerger7 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-20 13:28 UTC, opbld30 commented
Docs Build status updates of commit _[6c9cbbd](https://github.com/IeuanWalker/CommunityToolkit/commits/6c9cbbdbdd0ab68f23e800c1e0ce80748726197d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/converters/index.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-73) |
[docs/maui/converters/is-not-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-not-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-not-null-converter?branch=pr-en-us-73) |
[docs/maui/converters/is-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-null-converter?branch=pr-en-us-73) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204201327070995-73%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T13%3A28%3A05Z&sr=b&sp=r&sig=zZ%2Fh976X5P3eFsV3RycnaeeT2%2BVLNSuPn02yy8Cx4Ic%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 13:28 UTC, PRMerger4 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-20 13:29 UTC, opbld33 commented
Docs Build status updates of commit _[5f1ea6c](https://github.com/IeuanWalker/CommunityToolkit/commits/5f1ea6caef05b3ce0e28a3ec5bdf9d219584b4d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/converters/index.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-73) |
[docs/maui/converters/is-not-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-not-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-not-null-converter?branch=pr-en-us-73) |
[docs/maui/converters/is-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-null-converter?branch=pr-en-us-73) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204201326309402-73%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T13%3A28%3A59Z&sr=b&sp=r&sig=6tqaZNPfSfzsxUVCJBdfjfrtpZBkpoKnpt35IhlMqKg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 13:29 UTC, PRMerger-2 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-20 14:53 UTC, jfversluis reviewed
Fixing my own code formatting things here...

2022-04-20 14:53 UTC, jfversluis commented on docs/maui/converters/is-not-null-converter.md
> +	Content = label;
```suggestion
		label.SetBinding(
			Label.IsVisibleProperty,
			new Binding(nameof(ViewModels.MyObject), converter: new IsNotNullConverter()));

		Content = label;
```

2022-04-20 14:54 UTC, opbld32 commented
Docs Build status updates of commit _[351151a](https://github.com/IeuanWalker/CommunityToolkit/commits/351151affea1f9735a6267660928666abee0f7da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/converters/index.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-73) |
[docs/maui/converters/is-not-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-not-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-not-null-converter?branch=pr-en-us-73) |
[docs/maui/converters/is-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-null-converter?branch=pr-en-us-73) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204201453395948-73%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T14%3A54%3A27Z&sr=b&sp=r&sig=sc9RzHfAPrKO%2BC41l4FZZJvwwAwZh9HwfI3y9v1krrg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 14:54 UTC, PRMerger12 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-20 14:57 UTC, opbld30 commented
Docs Build status updates of commit _[70ae49a](https://github.com/IeuanWalker/CommunityToolkit/commits/70ae49a61c8776497e14d11f41bdbea7ad52c702)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/maui/converters/index.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/index?branch=pr-en-us-73) |
[docs/maui/converters/is-not-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-not-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-not-null-converter?branch=pr-en-us-73) |
[docs/maui/converters/is-null-converter.md](https://github.com/MicrosoftDocs/CommunityToolkit/blob/main/docs/maui/converters/is-null-converter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/communitytoolkit/maui/converters/is-null-converter?branch=pr-en-us-73) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C4%5C20%5C42ce6443-b3af-1e1b-1f87-f62bfbd983d2%5CPullRequest%5C202204201456376963-73%5Cworkflow_report.html?sv=2021-04-10&se=2022-05-21T14%3A57%3A23Z&sr=b&sp=r&sig=sJwaojc9WDuLiOiSfupH1APecbsj61w%2FtL5kWIBZtVY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/42ce6443-b3af-1e1b-1f87-f62bfbd983d2?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-04-20 14:57 UTC, PRMerger10 commented
## PRMerger Results
 | Issue | Description |
 --- | --- |
 Added File(s) | This PR contains added files. New files require human review.
 File Change Percent | This PR contains file(s) with more than 20% file change.
 Index File | This PR contains a change to the index file.

2022-04-20 14:58 UTC, jfversluis approved these changes
Thanks so much for your time and patience here @IeuanWalker !

2022-04-20 14:58 UTC, merged